In [1]:
import numpy as np

In [2]:
a = np.array([2,3,5,7,8])

In [3]:
a[0]

2

In [4]:
a[1:3]

array([3, 5])

In [5]:
a[2:-1]

array([5, 7])

In [10]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [11]:
c = np.arange(1,3,0.2)
c

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8])

In [12]:
a.dtype

dtype('int64')