In [4]:
import numpy as np

In [5]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 平方根を計算する
np.sqrt(arr)

In [ ]:
# 自然対数の底ｅの累乗
np.exp(arr)

In [6]:
# 正規分布に従う乱数
A = np.random.randn(10)

A

array([ 2.88777702, -1.43187814, -1.74820699,  1.40089958, -0.44500563,
       -0.70440762, -1.01699022, -0.05571216, -0.68721741,  0.20972047])

In [7]:
# 別のアレイも用意
B = np.random.randn(10)
B

array([-2.59954494, -1.56404478, -0.27053361,  0.00908156,  2.41672478,
       -0.95428872, -0.16826629, -0.95234542,  1.62752606,  0.11526592])

In [8]:
# 2つのアレイを足す
np.add(A,B)

array([ 0.28823208, -2.99592292, -2.01874059,  1.40998114,  1.97171915,
       -1.65869634, -1.1852565 , -1.00805758,  0.94030865,  0.32498639])

In [9]:
# 各要素の大きいほうを返す
np.maximum(A,B)

array([ 2.88777702, -1.43187814, -0.27053361,  1.40089958,  2.41672478,
       -0.70440762, -0.16826629, -0.05571216,  1.62752606,  0.20972047])

In [3]:
# この他の演算子に関しては、numpyのドキュメントに詳しい情報があります。
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True