In [1]:
import numpy as np

In [17]:
arr = np.arange(1,10).reshape(3,3)

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr2 = np.copy(arr)

In [23]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr * arr2 #要素ごとの積

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [26]:
np.dot(arr, arr2) #行列の積

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [27]:
arr.T #転置行列

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [29]:
arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
arr3 = np.arange(27).reshape(3,3,3)

In [31]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])