配列の作成

In [1]:
import numpy as np

In [7]:
X = np.array([[1,2], [2,3], [3,4], [4,5], [5,6], [6,7], [7,9]])
labels = np.array([0,1,2,0,1,2,0])

クラスタ0に属する点のみを取り出す

In [8]:
X[labels == 0, :]

array([[1, 2],
       [4, 5],
       [7, 9]])

重心の計算

In [11]:
X[labels == 0, :].mean(axis=0) #縦方向の平均値を求める

array([4.        , 5.33333333])

クラスタの中心

In [13]:
cluster_centers = np.array([[1,1],[2,2],[3,3]])

距離の二乗の計算

In [14]:
((X[:, :, np.newaxis] - cluster_centers.T[np.newaxis, :, :])**2).sum(axis=1)

array([[  1,   1,   5],
       [  5,   1,   1],
       [ 13,   5,   1],
       [ 25,  13,   5],
       [ 41,  25,  13],
       [ 61,  41,  25],
       [100,  74,  52]])

処理を分割した場合

In [15]:
p = X[:, :, np.newaxis] #Xを添字が3つの配列に変換し、[i, j]成分を[i, j, 0]成分に変換
q = cluster_centers.T[np.newaxis, :, :] #重心の配列を3つの配列に変換し、[k, l]成分を[0, k, l]成分に変換
r = (p - q)**2 #r[i, k, j] = (p[i, k] - q[k, j])^2 を計算
s = r.sum(axis = 1) #kについての和を取る

クラスタ中心のインデックス番号

In [24]:
s.argmin(axis=1)

array([0, 1, 2, 2, 2, 2, 2])